### ISSUE TITLE
The posibility to show  a text that must be marked as agreeed by the user before start the buy

### ISSUE THREAD

**Issue by vicencarlos** [sebsoftnl/moodle-enrol_gwpayments#10]
Many times, before start the buy process, it must be shown to the user, a legal text with conditions and policies that apply to the buy.

**Comment by rogiervandongen** [comment]
@vicencarlos 
I'm not sure whether or not this should be the responsibility of the plugin.
It may be a better idea to facilitate this through some other consent mechanism such as, for example, site policies.
In any case, please do not add this to the enrol_gwpayments plugin. This type of functionality should/must be enabled on a lower level (as mentioned: site policies or maybe even the core payment functionality)
