### ISSUE TITLE
Error when deleting coupon

### ISSUE THREAD

**Issue by papahepcat** [sebsoftnl/moodle-enrol_gwpayments#13]
When I try to delete a coupon, I get the following errors:
Notice: Trying to get property 'courseid' of non-object in /<<mymoodleinstance>>/enrol/gwpayments/classes/local/coupons/coupondelete.php on line 53

Warning: Creating default object from empty value in /<<mymoodleinstance>>/enrol/gwpayments/classes/local/coupons/coupondelete.php on line 56

Notice: Undefined property: stdClass::$validfrom in /<<mymoodleinstance>>/enrol/gwpayments/classes/local/coupons/coupondelete.php on line 58

Notice: Undefined property: stdClass::$validto in /<<mymoodleinstance>>/enrol/gwpayments/classes/local/coupons/coupondelete.php on line 59

Then a message that the coupon has been deleted. But the coupon remains

**Comment by rogiervandongen** [comment]
@papahepcat 
Is/will be fixed in next release.
