### ISSUE TITLE
Payment can not be done

### ISSUE THREAD

**Issue by nikk-sem** [sebsoftnl/moodle-enrol_gwpayments#14]
I have added the payment gateway of stripe and also added the payment account using the API key and Secret Key of stripe but when I tried to do payment of any course it is showing me an error.

 
![error this file could not be found](https://user-images.githubusercontent.com/108007606/175049665-00b4027f-1bbb-422d-9d95-1e2a64869d0b.png)

**Comment by sebastianberm** [comment]
Hi,
Would it be possible to mention the version of Moodle you're using, so we can investigate this?

**Comment by nikk-sem** [comment]
> Hi, Would it be possible to mention the version of Moodle you're using, so we can investigate this?

We are using Moodle 3.10 (Build: 20201109)

**Comment by rogiervandongen** [comment]
@nikk-sem 
Is this still an issue? Since the stripe payment gateway is not maintained nor written by us, we may not be able to investigate.
I suspect the problem is likely to exist in the Stripe plugin, in which case there would bge little we can do.

**Comment by rogiervandongen** [comment]
Closing as not relevant (this is not a stripe plugin)
