### ISSUE TITLE
Missing strings

### ISSUE THREAD

**Issue by ewallah** [sebsoftnl/moodle-enrol_gwpayments#17]
When visiting the admin/message.php page, you see 2 errors

`Invalid get_string() identifier: 'messageprovider:expiry_notification' or component 'enrol_gwpayments'. Perhaps you are missing $string['messageprovider:expiry_notification'] = ''; in enrol/gwpayments/lang/en/enrol_gwpayments.php?`

`Invalid get_string() identifier: 'messageprovider:gwpayments_enrolment' or component 'enrol_gwpayments'. Perhaps you are missing $string['messageprovider:gwpayments_enrolment'] = ''; in enrol/gwpayments/lang/en/enrol_gwpayments.php?`

**Comment by rogiervandongen** [comment]
@ewallah 
Is/will be fixed in next release.
