### ISSUE TITLE
Error when deleting coupons

### ISSUE THREAD

**Issue by 8com-Moodle** [sebsoftnl/moodle-enrol_gwpayments#18]
Hi,
When I tried to delete coupons. I got this error message and no one of the coupons can be deleted.

![tesss](https://github.com/sebsoftnl/moodle-enrol_gwpayments/assets/165896985/8858cdb7-5ddc-43ea-a2d3-38f234a3800e)

**Comment by dreblen** [comment]
The following is based on our experience with the same issue in Moodle 4.3.2.

The error seems to be coming from the fact that the "Delete Coupon" form is having two hidden inputs added with the name "id" (one from `\classes\local\coupons\coupondelete.php:65` and one from `\classes\local\coupons\controller.php:181`). The first one never gets a value, so while the second is (partially) processed successfully, the first one results in a failed lookup at `\classes\local\coupons\controller.php:184`.

Here is a possible fix for the problem: [20240506-delete-coupon.patch](https://github.com/sebsoftnl/moodle-enrol_gwpayments/files/15223087/20240506-delete-coupon.patch)

**Comment by 8com-Moodle** [comment]
worked. thanks.

**Comment by 8com-Moodle** [comment]
worked. thanks.

**Comment by dreblen** [comment]
Is there a chance of this being fixed in an official release? My environment doesn't really allow for self-maintained patches.

**Comment by sebastianberm** [comment]
Yes, however, this is one of the open source projects, so we only have a limited amount of time per project.
That being said, I'll create an upstream release later today.
